HWAHAE_SERVER_API_ALB = "hh-dev-nlb-main-api-CVJ-937b08504f104530.elb.ap-northeast-2.amazonaws.com"
HWAHAE_SERVER_API_VERSION = "v14"
AD_SERVING_SERVER_API_ALB =	"hh-dev-nlb-ad-serv-api-ASA-b378ab1b2064238e.elb.ap-northeast-2.amazonaws.com"
COMMERCE_SERVER_API_ALB = "hh-dev-nlb-cm-api-cb01eea7d3e8be5a.elb.ap-northeast-2.amazonaws.com"
HWAHAE_JSP = "dev-legacy.hwahae.co.kr/hwahae_jsp"
HWAHAE_SEARCH_SERVER = "hh-dev-nlb-search-api-esa-8b3b3d0c339d346d.elb.ap-northeast-2.amazonaws.com"
HWAHAE_SEARCH_SERVER_VERSION = "v1"
